version : "3.9"

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    networks:
      - hosting-network
    container_name: express-server
    restart: unless-stopped

  clients:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - hosting-network
    container_name: react-client
    restart: unless-stopped
    depends_on:
      - server


networks:
  hosting-network:
    driver: bridge